dubbo:
  application:
    name: demo-gwtcrud-provider # 应用名
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 9527
    name: dubbo
  provider:
    timeout: 1000
    filter: -exception
    HandleService:
      version: 1.0.0
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1:3306/mygwt?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

